doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Player:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Player/Model'
                prefix: 'Player\Model'
                alias: Player
            Identity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Identity/Model'
                prefix: 'Identity\Model'
                alias: Identity
            Roulette:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Roulette/Model'
                prefix: 'Roulette\Model'
                alias: Roulette

