roulette:
    resource: ../../src/Roulette/Api/Controller/
    type: annotation
player:
    resource: ../../src/Player/Api/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
